version: '3.8'

services:
  app:
    build: . 
    volumes: 
      - .:/djangoproject
    ports:
      - 8000:8000
    image: mytaxi:django
    container_name: mytaxi
    command: python manage.py runserver 0.0.0.0:8000

    