# Generated by Django 4.1.6 on 2023-03-28 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("billCode", models.CharField(blank=True, max_length=50, null=True)),
                ("billName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billDescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billTo", models.CharField(blank=True, max_length=255, null=True)),
                ("billEmail", models.EmailField(blank=True, max_length=254, null=True)),
                ("billPhone", models.CharField(blank=True, max_length=255, null=True)),
                ("billStatus", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billpaymentStatus",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentChannel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billpaymentInvoiceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billSplitPayment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billSplitPaymentArgs", models.TextField(blank=True, null=True)),
                (
                    "billpaymentSettlement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentSettlementDate",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "SettlementReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billPaymentDate", models.DateTimeField(blank=True, null=True)),
                (
                    "billExternalReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverEwallet",
            fields=[
                (
                    "driver_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ewallet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MYR", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("billCode", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MYR", max_length=3)),
                ("payment_method", models.CharField(default="fpx", max_length=50)),
                ("payment_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("refno", models.CharField(blank=True, max_length=255, null=True)),
                ("order_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bill",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billpertrans",
                        to="payment.bill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="payment",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentpertrans",
                to="payment.payment",
            ),
        ),
    ]
