# Generated by Django 4.2 on 2023-05-14 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("billCode", models.CharField(blank=True, max_length=50, null=True)),
                ("billName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billDescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billTo", models.CharField(blank=True, max_length=255, null=True)),
                ("billEmail", models.EmailField(blank=True, max_length=254, null=True)),
                ("billPhone", models.CharField(blank=True, max_length=255, null=True)),
                ("billStatus", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billpaymentStatus",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentChannel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billpaymentInvoiceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billSplitPayment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billSplitPaymentArgs", models.TextField(blank=True, null=True)),
                (
                    "billpaymentSettlement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentSettlementDate",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "SettlementReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billPaymentDate", models.DateTimeField(blank=True, null=True)),
                (
                    "billExternalReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriverEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "earning_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("earning_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
