# Generated by Django 4.1.6 on 2023-03-28 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billDescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billTo", models.CharField(blank=True, max_length=255, null=True)),
                ("billEmail", models.EmailField(blank=True, max_length=254, null=True)),
                ("billPhone", models.CharField(blank=True, max_length=255, null=True)),
                ("billStatus", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billpaymentStatus",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentChannel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billpaymentInvoiceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billSplitPayment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billSplitPaymentArgs", models.TextField(blank=True, null=True)),
                (
                    "billpaymentSettlement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billpaymentSettlementDate",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "SettlementReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billPaymentDate", models.DateTimeField(blank=True, null=True)),
                (
                    "billExternalReferenceNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
