# Generated by Django 4.1.7 on 2023-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_driverewallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionhistory",
            name="payment_date",
            field=models.DateTimeField(),
        ),
    ]
