# Generated by Django 4.1.7 on 2023-04-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_request", "0002_rename_actual_fare_riderequest_price"),
        ("payment", "0003_alter_commissionhistory_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "earning_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("earning_date", models.DateTimeField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride_request_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_request.riderequest",
                    ),
                ),
            ],
        ),
    ]
