# Generated by Django 4.1.6 on 2023-03-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0001_initial"),
        ("payment", "0003_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverEwallet",
            fields=[
                (
                    "driver_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ewallet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MYR", max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
