# Generated by Django 4.1.6 on 2023-03-31 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_remove_bill_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverewallet",
            old_name="driver_id",
            new_name="user",
        ),
    ]
