# Generated by Django 4.1.7 on 2023-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_driverearning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverearning",
            name="earning_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
