# Generated by Django 4.1.6 on 2023-03-28 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="ride_request",
        ),
    ]
