# Generated by Django 4.1.7 on 2023-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_driverearning_earning_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionhistory",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
