# Generated by Django 4.1.6 on 2023-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_remove_payment_ride_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="refno",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
