# Generated by Django 4.1.7 on 2023-04-14 23:04

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("return_url", models.TextField(blank=True, null=True)),
                ("advertiser", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="advertisement_images",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("rental_time_from", models.DateTimeField(blank=True, null=True)),
                ("rental_time_to", models.DateTimeField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
