# Generated by Django 4.1.7 on 2023-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("4pax", "4 Seater"), ("6pax", "6 Seater")],
                max_length=128,
                null=True,
            ),
        ),
    ]
