# Generated by Django 4.1.6 on 2023-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverlocation",
            name="polygon",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
