# Generated by Django 4.1.7 on 2023-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_driver_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Block",
        ),
    ]
