# Generated by Django 4.2 on 2023-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
