# Generated by Django 4.1.6 on 2023-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_driver_statusdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='statusDriver',
            field=models.CharField(blank=True, choices=[('submitting', 'Submitting'), ('pending', 'Pending'), ('activated', 'Activated'), ('failed', 'Failed'), ('verified', 'Verified')], default='submitting', max_length=20, null=True),
        ),
    ]
