# Generated by Django 4.1.7 on 2023-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_location_keywords_alter_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="administrativeArea",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="subAdministrativeArea",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
