# Generated by Django 4.1.6 on 2023-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_driver_statusdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='statusMessage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
