# Generated by Django 4.1.7 on 2023-04-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0005_remove_location_polygon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="administrativeArea",
            new_name="locality",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="subAdministrativeArea",
            new_name="subLocality",
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("lat", models.CharField(max_length=255)),
                ("lng", models.CharField(max_length=255)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="rides.location",
                    ),
                ),
            ],
        ),
    ]
