# Generated by Django 4.1.6 on 2023-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_driver_statusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
