# Generated by Django 4.2 on 2023-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0007_alter_driverlocation_polygon"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="polygon",
            field=models.TextField(blank=True, null=True),
        ),
    ]
