# Generated by Django 4.1.6 on 2023-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_driverrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='jobDriverStatus',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('enroute_pickup', 'Heading to Passenger'), ('waiting_pickup', 'Waiting for Passenger'), ('in_transit', 'In Transit with Passenger')], max_length=50, null=True),
        ),
    ]
