# Generated by Django 4.1.6 on 2023-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_driver_jobdriverstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ride_request',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
