# Generated by Django 4.2 on 2023-06-26 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserOTP",
        ),
    ]
