# Generated by Django 4.1.7 on 2023-04-04 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentid",
            name="student_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="student-pic/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
