# Generated by Django 4.1.7 on 2023-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0002_studentid_student_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("alumni", "Alumni"),
                    ("outsider", "Outsider"),
                ],
                max_length=10,
            ),
        ),
    ]
