# Generated by Django 4.1.6 on 2023-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='dropoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
