# Generated by Django 4.1.7 on 2023-04-03 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riderequest",
            old_name="actual_fare",
            new_name="price",
        ),
    ]
