# Generated by Django 4.2 on 2023-05-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        ("ride_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_rides",
                to="rides.driver",
            ),
        ),
    ]
