# Generated by Django 4.1.6 on 2023-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0002_alter_riderequest_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_polygon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_polygon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
