# Generated by Django 4.1.7 on 2023-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0002_rename_actual_fare_riderequest_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("4pax", "4 Seater"), ("6pax", "6 Seater")],
                max_length=255,
                null=True,
            ),
        ),
    ]
