# Generated by Django 4.1.6 on 2023-03-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0003_riderequest_dropoff_polygon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='dropoff_polygon',
            new_name='route_polygon',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='pickup_polygon',
        ),
    ]
