# Generated by Django 4.1.7 on 2023-04-09 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0003_riderequest_vehicle_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
