# Generated by Django 4.2 on 2023-05-14 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_request", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassengerCancel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cancel_rate", models.IntegerField(blank=True, default=0, null=True)),
                ("warning_rate", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cumulative_penalty",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "is_disable",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_request.passenger",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
