# Generated by Django 4.1.7 on 2023-04-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0004_popularlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularlocation",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="popularlocation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="popularlocation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="popularlocation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
