# Generated by Django 4.1.7 on 2023-04-09 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0005_alter_popularlocation_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularlocation",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="popular-location/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
