# Generated by Django 4.1.7 on 2023-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0006_popularlocation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularlocation",
            name="administrativeArea",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="popularlocation",
            name="subAdministrativeArea",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
