# Generated by Django 4.1.7 on 2023-04-09 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0007_popularlocation_administrativearea_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="popularlocation",
            old_name="administrativeArea",
            new_name="locality",
        ),
        migrations.RenameField(
            model_name="popularlocation",
            old_name="subAdministrativeArea",
            new_name="subLocality",
        ),
    ]
