# Generated by Django 4.1.7 on 2023-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ride_request",
            "0008_rename_administrativearea_popularlocation_locality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="passenger_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
