# Generated by Django 4.1.7 on 2023-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0009_alter_passenger_passenger_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="special_requests",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
