# Generated by Django 4.1.7 on 2023-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0010_alter_riderequest_special_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="route_polygon",
            field=models.TextField(blank=True, null=True),
        ),
    ]
