# Generated by Django 4.1.7 on 2023-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0011_alter_riderequest_route_polygon"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="isFemaleDriver",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
