# Generated by Django 4.2 on 2023-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0012_riderequest_isfemaledriver"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="isRated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
