# Generated by Django 4.2 on 2023-05-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0014_cancelratedriver"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelratedriver",
            name="warning_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
