# Generated by Django 4.2 on 2023-05-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0008_location_polygon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_request", "0015_cancelratedriver_warning_start_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderequest",
            name="rating",
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rides.driver"
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_request.riderequest",
                    ),
                ),
            ],
        ),
    ]
