# Generated by Django 4.2 on 2023-05-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0008_location_polygon"),
        ("ride_request", "0016_remove_riderequest_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rides.driver",
            ),
        ),
    ]
