# Generated by Django 4.2 on 2023-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_request", "0017_alter_rating_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderequest",
            name="isRated",
        ),
        migrations.AddField(
            model_name="rating",
            name="isRated",
            field=models.BooleanField(default=False),
        ),
    ]
